### ISSUE TITLE
SIGSEGV when loading hello world example pass

### ISSUE THREAD

**Issue by unknowntrojan** [jamesmth/llvm-plugin-rs#5] opened 2023-02-06 21:03 UTC
Hello,

A few months ago I ported this repo to LLVM 15 to use with the rust compiler, but whenever I tried loading the produced passes, I would get a SIGSEGV in rustc. At the time I thought this was entirely my fault, and gave up due to time constraints and the difficulty of debugging something inside WSL. However, now that this repo has properly been updated to LLVM 15, I gave it another shot, but I'm getting the same issue. When compiling the hello world pass example and loading it into a test program I get this error message:

![](https://i.imgur.com/1HlS3lf.png)

To reproduce:
- Compile the hello-world example pass.
- Create a new project with `cargo init --bin`
- In the file `.cargo/config.toml`, under `build.rustflags`, add an option `-Zllvm-plugins=(PATH_TO_PASS)` and `-Cpasses=hello-world`.
- Compile the new project.

Please let me know if you can reproduce it or if I'm doing something completely wrong. I'm gonna try to investigate a bit further, but I'm not experienced in working with rustc, so any help would be appreciated.

**Comment by unknowntrojan** [comment] 2023-02-06 23:53
After some more investigation, it appears to be a null ptr deref in PassManager::run.
I compiled rustc myself, and using that version compiled in debug mode, the pass ran just fine. Maybe a slight difference in LLVM version is causing the issue or it's one of those nasty bugs that only come out when compiled in release.

**Comment by jamesmth** [comment] 2023-02-11 14:20
Hello,

I investigated a bit and couldn't manage to reproduce the error. I tried several recent nightly versions and the `hello-world` example worked just fine.

You should make sure that:
- The `rustc` version uses LLVM-15 (can be checked with `rustc -vV`)
- The example plugin links (at runtime) to the **same** LLVM binary as `rustc`. This can be enforced by creating a symlink before compiling your crate with the plugin:
```
$ rustup install "nightly-$NIGHTLY" --profile=minimal
$ RUSTC=$(rustc +nightly-$NIGHTLY -V | awk '{ print $2 }')
$ ln -s "$HOME/.rustup/toolchains/nightly-$NIGHTLY-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-$RUSTC.so" libLLVM-15.so
$ LD_LIBRARY_PATH=. cargo "+nightly-$NIGHTLY" b
```

Could you provide me with the exact version of the compiler where the SIGSEGV occurs?

**Comment by unknowntrojan** [comment] 2023-02-13 08:21
the version that crashes for me is "rustc 1.68.0-nightly (935dc0721 2022-12-19)". I tried the symlink but even then the SIGSEGV still occurs (probably linker shenanigans). It's probably a mismatched LLVM version, the version the crashing rustc uses is 15.0.6, while my system's libraries are on 15.0.7. This is probably why compiling rustc myself fixes the issues.

**Comment by jamesmth** [comment] 2023-02-15 17:52
That's probably it. I'm closing the issue since there is not much I can do about it.

**Closed by jamesmth** 2023-02-15 17:52 UTC
